const PEOPLE_ADD_REQUEST = 'PEOPLE_ADD_REQUEST';
const PEOPLE_ADD_START = 'PEOPLE_ADD_START';
const PEOPLE_ADD_SUCCESS = 'PEOPLE_ADD_SUCCESS';
const PEOPLE_ADD_FAIL = 'PEOPLE_ADD_FAIL';

const PEOPLE_GET_REQUEST = 'PEOPLE_GET_REQUEST';
const PEOPLE_GET_START = 'PEOPLE_GET_START';
const PEOPLE_GET_SUCCESS = 'PEOPLE_GET_SUCCESS';
const PEOPLE_GET_FAIL = 'PEOPLE_GET_FAIL';

const PEOPLE_IS_DRAGGING_REQUEST = 'PEOPLE_IS_DRAGGING_REQUEST';
const PEOPLE_IS_DRAGGING = 'PEOPLE_IS_DRAGGING';

const PEOPLE_UNMOUNT_REQUEST = 'PEOPLE_UNMOUNT_REQUEST';
const PEOPLE_UNMOUNT_SUCCESS = 'PEOPLE_UNMOUNT_SUCCESS';

export default {
    PEOPLE_ADD_REQUEST,
    PEOPLE_ADD_START,
    PEOPLE_ADD_SUCCESS,
    PEOPLE_ADD_FAIL,
    PEOPLE_GET_REQUEST,
    PEOPLE_GET_START,
    PEOPLE_GET_SUCCESS,
    PEOPLE_GET_FAIL,
    PEOPLE_IS_DRAGGING_REQUEST,
    PEOPLE_IS_DRAGGING,
    PEOPLE_UNMOUNT_REQUEST,
    PEOPLE_UNMOUNT_SUCCESS
}