const GET_CONFERENCES_REQUEST = 'GET_CONFERENCES_REQUEST';
const GET_CONFERENCES = 'GET_CONFERENCES';
const GET_CONFERENCES_SUCCESS = 'GET_CONFERENCES_SUCCESS';
const GET_CONFERENCES_FAIL = 'GET_CONFERENCES_FAIL';

const SELECT_CONF = 'SELECT_CONF';

const LAZY_GET_CONFERENCES_REQUEST = 'LAZY_GET_CONFERENCES_REQUEST';
const LAZY_GET_CONFERENCES = 'LAZY_GET_CONFERENCES';
const LAZY_GET_CONFERENCES_SUCCESS = 'LAZY_GET_CONFERENCES_SUCCESS';
const LAZY_GET_CONFERENCES_FAIL = 'LAZY_GET_CONFERENCES_FAIL';

export const ADD_PERSON_REQUEST = `ADD_PERSON_REQUEST`
export const ADD_PERSON_SUCCESS = `ADD_PERSON_SUCCESS`
export const ADD_PERSON_FAIL = `ADD_PERSON_FAIL`

export const DELETE_PERSON_REQUEST = `DELETE_PERSON_REQUEST`
export const DELETE_PERSON_SUCCESS = `DELETE_PERSON_SUCCESS`
export const DELETE_PERSON_FAIL = `DELETE_PERSON_FAIL`

export default {
    GET_CONFERENCES_REQUEST,
    GET_CONFERENCES,
    GET_CONFERENCES_SUCCESS,
    GET_CONFERENCES_FAIL,
    SELECT_CONF,
    LAZY_GET_CONFERENCES_REQUEST,
    LAZY_GET_CONFERENCES,
    LAZY_GET_CONFERENCES_SUCCESS,
    LAZY_GET_CONFERENCES_FAIL,
    ADD_PERSON_REQUEST,
    ADD_PERSON_SUCCESS,
    ADD_PERSON_FAIL,
    DELETE_PERSON_REQUEST,
    DELETE_PERSON_SUCCESS,
    DELETE_PERSON_FAIL
}