const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER = 'REGISTER';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';

const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
const LOG_IN = 'LOG_IN';
const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
const LOG_IN_FAIL = 'LOG_IN_FAIL';

const ADD_PEOPLE = 'ADD_PEOPLE';
const ADD_PEOPLE_REQUEST = 'ADD_PEOPLE_REQUEST';



export default {
    REGISTER_REQUEST,
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    LOG_IN_REQUEST,
    LOG_IN,
    LOG_IN_SUCCESS,
    LOG_IN_FAIL,
    ADD_PEOPLE,
    ADD_PEOPLE_REQUEST
}